package:
  name: etiennevar
  version: 1.0.0

source:
  path: ../  # ou le chemin vers ta source

build:
  noarch: python
  script: pip install .

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.8

test:
  commands:
    - etiennevar --help

about:
  home: https://github.com/etiennekabongo/etiennevar
  license: MIT
  summary: "Outil en ligne de commande pour résumer les fichiers VCF."

extra:
  recipe-maintainers:
    - etiennekabongo

